groups:
  - name: topolvm
    rules:
      - alert: AvailableBytesHighUtilizationInShortTerm
        expr: |
          sum(predict_linear(topolvm_volumegroup_available_bytes[1h], 3600*24)) without (instance,node) <= 0
        labels:
          severity: warning
        for: 10m
        annotations:
          summary: Total available bytes of CS nodes will be exhausted in 1 day.
          runbook: Please check the disk utilization of applications and contact the developer team.
      - alert: AvailableBytesHighUtilizationInLongTerm
        expr: |
          sum(predict_linear(topolvm_volumegroup_available_bytes[1h], 3600*24*30)) without (instance,node) <= 0
        labels:
          severity: warning
        for: 1h
        annotations:
          summary: Total available bytes of CS nodes will be exhausted in 1 month.
          runbook: Please consider the disk allocation policy and the equipment planning.
