apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-gorush.yaml
  - app-kodama.yaml
  - app-misc.yaml
  - app-monitoring.yaml
  - app-oauth-redirector.yaml
  - elastic-serviceaccount.yaml
  - maneki.yaml
  - project.yaml
commonLabels:
  team: maneki
