apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common.yaml
  - rbac.yaml
  - service-contour.yaml
  - certificate.yaml
  - deployment.yaml
  - pdb.yaml
  - rbac_contour-plus.yaml
  - service.yaml
