apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/all-in-one.yaml
patchesStrategicMerge:
  - statefulset.yaml
  - crd.yaml
  - validatingwebhookconfiguration.yaml
